# Specify the Xcode version to use
macos:
  xcode: "9.2.0"
shell: /bin/bash --login -eo pipefail

steps:
  - checkout
  - run: git submodule sync
  - run: git submodule update --init --remote
  - run:

      name: Set Ruby Version
      command: echo "ruby-2.4" > ~/.ruby-version

  - restore_cache:
      key: 1-gems-{{ checksum "Gemfile.lock" }}

  - run: bundle check || bundle install --path vendor/bundle

  - save_cache:
      key: 1-gems-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

  - restore_cache:
      key: 1-pods-{{ checksum "Podfile.lock" }}
  - run:
      name: Install CocoaPods
      command: |
        curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
        bundle exec pod install
  - save_cache:
      key: 1-pods-{{ checksum "Podfile.lock" }}
      paths:
        - ./Pods

  # Build the app
  - run:
      name: Build app
      command: |
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        bundle exec fastlane match adhoc
        bundle exec fastlane adhoc